#include "codegen/codegen.h"

#include <cstring>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <stdexcept>

namespace rasp {

namespace {

int64_t int_imm_value(const Ref<PrimExpr>& expr) {
  if (!expr || expr->node_type() != IRNodeType::kIntImm) {
    throw std::runtime_error("Codegen: expected IntImm");
  }
  return std::static_pointer_cast<IntImm>(expr)->value;
}

bool is_const_buffer(const Ref<Buffer>& buf) {
  return !buf->data.empty();
}

bool is_output_buffer(const Ref<Buffer>& buf) {
  return buf->name == "output";
}

std::string float_literal(double value) {
  std::ostringstream os;
  os << std::setprecision(9) << value;
  std::string s = os.str();
  if (s.find('.') == std::string::npos &&
      s.find('e') == std::string::npos &&
      s.find('E') == std::string::npos) {
    s += ".0";
  }
  return s + "f";
}

} /* anonymous namespace */

void CodegenContext::emit(const std::string& line) {
  code << get_indent() << line << "\n";
}

std::string CodegenContext::get_indent() const {
  return std::string(static_cast<size_t>(indent_level) * 2, ' ');
}

void Codegen::generate(Ref<LLIRModule> mod, const std::string& output_path) {
  Codegen cg;
  cg.collect_buffers(mod);
  cg.emit_header();
  cg.emit_constants();
  for (auto& name : mod->exec_order) {
    cg.emit_prim_func(mod->get_func(name));
  }
  cg.emit_model_run(mod);
  cg.emit_meta();

  std::filesystem::path path(output_path);
  if (path.has_parent_path()) std::filesystem::create_directories(path.parent_path());
  std::ofstream out(output_path);
  if (!out) throw std::runtime_error("Codegen: failed to open " + output_path);
  out << cg.ctx_.code.str();
}

void Codegen::collect_buffers(Ref<LLIRModule> mod) {
  for (auto& name : mod->exec_order) {
    auto fn = mod->get_func(name);
    for (auto& buf : fn->params) {
      if (!buffers_.count(buf->name)) buffers_[buf->name] = buf;
      bool known = false;
      auto mark_known = [&](const std::vector<Ref<Buffer>>& vec) {
        for (auto& item : vec) {
          if (item->name == buf->name) return true;
        }
        return false;
      };
      known = mark_known(input_buffers_) || mark_known(output_buffers_) ||
              mark_known(const_buffers_) || mark_known(local_buffers_);
      if (known) continue;
      if (is_const_buffer(buf)) {
        const_buffers_.push_back(buf);
      } else if (is_output_buffer(buf)) {
        output_buffers_.push_back(buf);
      } else if (buf->scope == BufferScope::kGlobal) {
        input_buffers_.push_back(buf);
      } else {
        local_buffers_.push_back(buf);
      }
    }
  }
}

void Codegen::emit_header() {
  ctx_.emit("/* Generated by RASP Compiler. */");
  ctx_.emit("#include <algorithm>");
  ctx_.emit("#include <cmath>");
  ctx_.emit("#include <cstdint>");
  ctx_.emit("#include <cstdlib>");
  ctx_.emit("#include <cstring>");
  ctx_.emit("");
}

void Codegen::emit_constants() {
  for (auto& buf : const_buffers_) {
    if (buf->dtype != DataType::kFloat32) {
      throw std::runtime_error("Codegen: only float32 constants are supported");
    }
    const float* vals = reinterpret_cast<const float*>(buf->data.data());
    size_t n = buf->data.size() / sizeof(float);
    ctx_.emit("static const float " + buf->name + "[" + std::to_string(n) +
              "] __attribute__((aligned(16))) = {");
    ctx_.indent();
    std::ostringstream line;
    for (size_t i = 0; i < n; ++i) {
      line << float_literal(vals[i]);
      if (i + 1 != n) line << ", ";
      if ((i + 1) % 8 == 0 || i + 1 == n) {
        ctx_.emit(line.str());
        line.str("");
        line.clear();
      }
    }
    ctx_.dedent();
    ctx_.emit("};");
    ctx_.emit("");
  }
}

void Codegen::emit_prim_func(Ref<PrimFunc> func) {
  std::string sig = "static void " + func->name + "(";
  for (size_t i = 0; i < func->params.size(); ++i) {
    if (i) sig += ", ";
    sig += emit_buffer_param(func->params[i]);
  }
  sig += ") {";
  ctx_.emit(sig);
  ctx_.indent();
  emit_stmt(func->body);
  ctx_.dedent();
  ctx_.emit("}");
  ctx_.emit("");
}

void Codegen::emit_stmt(Ref<Stmt> stmt) {
  if (!stmt) return;
  switch (stmt->node_type()) {
    case IRNodeType::kSeqStmt: {
      auto seq = std::static_pointer_cast<SeqStmt>(stmt);
      for (auto& s : seq->seq) emit_stmt(s);
      return;
    }
    case IRNodeType::kFor: {
      auto loop = std::static_pointer_cast<For>(stmt);
      if (loop->kind == ForKind::kUnrolled) ctx_.emit("#pragma GCC unroll");
      ctx_.emit("for (int64_t " + loop->loop_var->name + " = " +
                emit_expr(loop->min) + "; " + loop->loop_var->name + " < (" +
                emit_expr(loop->min) + " + " + emit_expr(loop->extent) + "); ++" +
                loop->loop_var->name + ") {");
      ctx_.indent();
      emit_stmt(loop->body);
      ctx_.dedent();
      ctx_.emit("}");
      return;
    }
    case IRNodeType::kIfThenElse: {
      auto ite = std::static_pointer_cast<IfThenElse>(stmt);
      ctx_.emit("if (" + emit_expr(ite->condition) + ") {");
      ctx_.indent();
      emit_stmt(ite->then_case);
      ctx_.dedent();
      if (ite->else_case) {
        ctx_.emit("} else {");
        ctx_.indent();
        emit_stmt(ite->else_case);
        ctx_.dedent();
      }
      ctx_.emit("}");
      return;
    }
    case IRNodeType::kAllocate: {
      auto alloc = std::static_pointer_cast<Allocate>(stmt);
      std::string n = "1";
      for (auto& extent : alloc->extents) n += " * " + emit_expr(extent);
      ctx_.emit(ctype(alloc->dtype) + " " + alloc->buffer_var->name +
                "[" + n + "] __attribute__((aligned(16)));");
      emit_stmt(alloc->body);
      return;
    }
    case IRNodeType::kBufferStore: {
      auto store = std::static_pointer_cast<BufferStore>(stmt);
      ctx_.emit(store->buffer->name + "[" +
                linearize_indices(store->buffer, store->indices) +
                "] = " + emit_expr(store->value) + ";");
      return;
    }
    case IRNodeType::kEvaluate: {
      auto eval = std::static_pointer_cast<Evaluate>(stmt);
      ctx_.emit(emit_expr(eval->value) + ";");
      return;
    }
    default:
      throw std::runtime_error("Codegen: unsupported Stmt");
  }
}

std::string Codegen::emit_expr(Ref<PrimExpr> expr) {
  switch (expr->node_type()) {
    case IRNodeType::kLLVar:
      return std::static_pointer_cast<LLVar>(expr)->name;
    case IRNodeType::kIntImm:
      return std::to_string(std::static_pointer_cast<IntImm>(expr)->value);
    case IRNodeType::kFloatImm: {
      return float_literal(std::static_pointer_cast<FloatImm>(expr)->value);
    }
    case IRNodeType::kBufferLoad: {
      auto load = std::static_pointer_cast<BufferLoad>(expr);
      return load->buffer->name + "[" +
             linearize_indices(load->buffer, load->indices) + "]";
    }
    case IRNodeType::kAdd: {
      auto op = std::static_pointer_cast<Add>(expr);
      return "(" + emit_expr(op->a) + " + " + emit_expr(op->b) + ")";
    }
    case IRNodeType::kSub: {
      auto op = std::static_pointer_cast<Sub>(expr);
      return "(" + emit_expr(op->a) + " - " + emit_expr(op->b) + ")";
    }
    case IRNodeType::kMul: {
      auto op = std::static_pointer_cast<Mul>(expr);
      return "(" + emit_expr(op->a) + " * " + emit_expr(op->b) + ")";
    }
    case IRNodeType::kDiv: {
      auto op = std::static_pointer_cast<Div>(expr);
      return "(" + emit_expr(op->a) + " / " + emit_expr(op->b) + ")";
    }
    case IRNodeType::kMin: {
      auto op = std::static_pointer_cast<Min>(expr);
      return "std::min(" + emit_expr(op->a) + ", " + emit_expr(op->b) + ")";
    }
    case IRNodeType::kMax: {
      auto op = std::static_pointer_cast<Max>(expr);
      return "std::max(" + emit_expr(op->a) + ", " + emit_expr(op->b) + ")";
    }
    case IRNodeType::kSelect: {
      auto sel = std::static_pointer_cast<Select>(expr);
      return "((" + emit_expr(sel->condition) + ") ? " +
             emit_expr(sel->true_value) + " : " + emit_expr(sel->false_value) + ")";
    }
    case IRNodeType::kCast: {
      auto cast = std::static_pointer_cast<Cast>(expr);
      return "((" + ctype(cast->dtype) + ")(" + emit_expr(cast->value) + "))";
    }
    case IRNodeType::kLLCall: {
      auto call = std::static_pointer_cast<PrimCall>(expr);
      if (call->func_name == "and") {
        return "((" + emit_expr(call->args[0]) + ") && (" +
               emit_expr(call->args[1]) + "))";
      }
      if (call->func_name == "ge") {
        return "(" + emit_expr(call->args[0]) + " >= " + emit_expr(call->args[1]) + ")";
      }
      if (call->func_name == "lt") {
        return "(" + emit_expr(call->args[0]) + " < " + emit_expr(call->args[1]) + ")";
      }
      if (call->func_name == "sqrt") {
        return "std::sqrt(" + emit_expr(call->args[0]) + ")";
      }
      throw std::runtime_error("Codegen: unsupported PrimCall " + call->func_name);
    }
    default:
      throw std::runtime_error("Codegen: unsupported PrimExpr");
  }
}

std::string Codegen::emit_buffer_param(Ref<Buffer> buf) {
  std::string qual = (buf->scope == BufferScope::kGlobal && !is_output_buffer(buf))
    ? "const "
    : "";
  return qual + ctype(buf->dtype) + "* __restrict__ " + buf->name;
}

std::string Codegen::linearize_indices(Ref<Buffer> buf,
                                       const std::vector<Ref<PrimExpr>>& indices) {
  if (indices.size() == 1 && buf->shape.size() != 1) return emit_expr(indices[0]);
  std::string offset = "0";
  int64_t stride = 1;
  for (int i = static_cast<int>(indices.size()) - 1; i >= 0; --i) {
    offset = "(" + emit_expr(indices[i]) + " * " + std::to_string(stride) +
             " + " + offset + ")";
    if (i < static_cast<int>(buf->shape.size())) stride *= int_imm_value(buf->shape[i]);
  }
  return offset;
}

void Codegen::emit_model_run(Ref<LLIRModule> mod) {
  for (auto& buf : local_buffers_) {
    int64_t nbytes = ((buffer_numel(buf) * 4 + 15) / 16) * 16;
    ctx_.emit("static float* alloc_" + buf->name + "() {");
    ctx_.indent();
    ctx_.emit("return static_cast<float*>(std::aligned_alloc(16, " +
              std::to_string(nbytes) + "));");
    ctx_.dedent();
    ctx_.emit("}");
  }
  ctx_.emit("extern \"C\" void model_run(const float** inputs, float** outputs) {");
  ctx_.indent();
  for (size_t i = 0; i < input_buffers_.size(); ++i) {
    ctx_.emit("const float* " + input_buffers_[i]->name + " = inputs[" +
              std::to_string(i) + "];");
  }
  for (size_t i = 0; i < output_buffers_.size(); ++i) {
    ctx_.emit("float* " + output_buffers_[i]->name + " = outputs[" +
              std::to_string(i) + "];");
  }
  for (auto& buf : local_buffers_) {
    ctx_.emit("float* " + buf->name + " = alloc_" + buf->name + "();");
  }
  for (auto& name : mod->exec_order) {
    auto fn = mod->get_func(name);
    std::string call = fn->name + "(";
    for (size_t i = 0; i < fn->params.size(); ++i) {
      if (i) call += ", ";
      call += fn->params[i]->name;
    }
    call += ");";
    ctx_.emit(call);
  }
  for (auto& buf : local_buffers_) ctx_.emit("std::free(" + buf->name + ");");
  ctx_.dedent();
  ctx_.emit("}");
  ctx_.emit("");
}

void Codegen::emit_meta() {
  ctx_.emit("extern \"C\" int model_num_inputs() { return " +
            std::to_string(input_buffers_.size()) + "; }");
  ctx_.emit("extern \"C\" int model_num_outputs() { return " +
            std::to_string(output_buffers_.size()) + "; }");
  ctx_.emit("extern \"C\" int64_t model_input_numel(int index) {");
  ctx_.indent();
  ctx_.emit("static const int64_t values[] = {" + [&]() {
    std::string s;
    for (size_t i = 0; i < input_buffers_.size(); ++i) {
      if (i) s += ", ";
      s += std::to_string(buffer_numel(input_buffers_[i]));
    }
    return s;
  }() + "};");
  ctx_.emit("return values[index];");
  ctx_.dedent();
  ctx_.emit("}");
  ctx_.emit("extern \"C\" int64_t model_output_numel(int index) {");
  ctx_.indent();
  ctx_.emit("static const int64_t values[] = {" + [&]() {
    std::string s;
    for (size_t i = 0; i < output_buffers_.size(); ++i) {
      if (i) s += ", ";
      s += std::to_string(buffer_numel(output_buffers_[i]));
    }
    return s;
  }() + "};");
  ctx_.emit("return values[index];");
  ctx_.dedent();
  ctx_.emit("}");
}

int64_t Codegen::buffer_numel(Ref<Buffer> buf) const {
  int64_t n = 1;
  for (auto& dim : buf->shape) n *= int_imm_value(dim);
  return n;
}

std::string Codegen::ctype(DataType dtype) const {
  switch (dtype) {
    case DataType::kFloat32: return "float";
    case DataType::kInt32: return "int32_t";
    case DataType::kInt64: return "int64_t";
    case DataType::kBool: return "bool";
    default:
      throw std::runtime_error("Codegen: unsupported dtype");
  }
}

} /* namespace rasp */
